src/Entity/Commande.php
<?php

namespace App\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

   /**
     * @ORM\Column(type="datetime")
     */
    private $date_commande;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_livraison;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $poids;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\OneToMany(targetEntity=LigneCommande::class, mappedBy="commande", cascade={"persist"})
     */
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->id;
    }
   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getDateLivraison(): ?\DateTimeInterface
    {
        return $this->date_livraison;
    }

    public function setDateLivraison(\DateTimeInterface $date_livraison): self
    {
        $this->date_livraison = $date_livraison;

        return $this;
    }

    public function getPoids(): ?float
    {
        return $this->poids;
    }

    public function setPoids(?float $poids): self
    {
        $this->poids = $poids;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection<int, LigneCommande>
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getCommande() === $this) {
                $ligneCommande->setCommande(null);
            }
        }

        return $this;
    }

    
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        <!-- Inclure le CSS compilé -->
    <link href="{{ asset('build/app.css') }}" rel="stylesheet">

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
    
</html>

templates/impression.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Reçu de commande</title>
    <style>
        body {
            font-family: 'Courier New', Courier, monospace; /* Police monospacée pour une meilleure compatibilité */
            font-size: 14px; /* Taille réduite pour la largeur de l'imprimante */
            margin: 0;
            padding: 0;
        }
        .centered {
            text-align: center;
            font-weight: bold;
        }
        .info {
            margin-top: 10px;
            margin-bottom: 10px;
        }
        .info p {
            margin: 5px 0;
        }
        .line {
            border-top: 1px dashed black;
            margin: 10px 0;
        }
        .right {
            text-align: right;
        }
        .left {
            text-align: left;
        }
    </style>
    
</head>
<body>

    <div class="">
        <p><strong>RECU</strong></p>
        <p><strong>{{entreprise }}</strong></p>
        <p>{{ adresse }}</p>
        <p>{{ whatsapp }}</p>
    </div>

    <div class="line"></div>

    <div class="info">
        <p><strong>Numéro de commande:</strong> {{ commande.id }}</p>
        <p><strong>Date:</strong> {{ commande.dateCommande|date('d/m/Y') }}</p>
        <p><strong>Client:</strong> {{ commande.client.nom }}</p>
        <p><strong>Poids:</strong> {{ poids }} kg</p>
        <p><strong>Prix/kg:</strong> {{ prixKilo }} F cfa</p>
    </div>

    <div class="line"></div>

    <div class="">
        <p><strong>Total à payer:</strong> {{ poids * prixKilo }} FCFA</p>
        
    </div>

    <div class="line"></div>

    <div class="">
        <p><strong>{{ delai }}</strong></p>
        <p><strong>{{ penalty }}</strong> <br> <strong>{{ prix_penalty }}</strong> </p>
    </div>
    <p> Merci pour votre confiance </p>
    <br>


</body>



</html>

templates/print_receipt.html.twig
{% extends 'base.html.twig' %}

{% block title %}Impression du reçu{% endblock %}

{% block body %}
    <h1>Impression du reçu</h1>
    
    <p>Le reçu de votre commande est prêt à être consulté et imprimé. Cliquez sur le lien ci-dessous :</p>
    
    <a href="{{ pdfFilePath }}" target="_blank">Télécharger le reçu au format PDF</a>
    
    <p>Merci pour votre commande!</p>
{% endblock %}